name: fpga

on: [push, workflow_dispatch]
jobs:
  fpga:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Checkout tt-support-tools repo
        uses: actions/checkout@v4
        with:
          repository: psychogenic/tt-support-tools
          path: tt
          ref: efabless

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install tt-support-tools dependencies
        shell: bash
        run: pip install -r tt/requirements.txt

      - name: Install Python packages
        if: ${{ hashFiles('test/requirements.txt') != '' }}
        shell: bash
        run: pip install -r test/requirements.txt

      - name: Fetch verilog and build config
        shell: bash
        run: |
          python tt/tt_tool.py --create-user-config $FLOW_ARG

      - name: install oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          python-override: true

      - name: Create the bitstream
        shell: bash
        run: |
          python tt/tt_tool.py fpga --board efab_explain --create-bitstream
          
      
      - name: Create the UF2
        shell: bash
        run: |
          CLOCKRATE=`python tt/tt_tool.py info --clock_hz`
          TITLE=`python tt/tt_tool.py info --title`
          python tt/fpga/bitstream_to_uf2.py --target efabless --slot 1 --name "$TITLE" --autoclock $CLOCKRATE build/tt_fpga.bin build/tt_fpga.uf2

      - name: Upload the bitstream
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fpga_bitstream
          path: |
            build/*
            docs/*
            src/*
            info.yaml
            LICENSE
